Create packaging for libnetfilter_conntrack, use version 1.0.9.
sailfishos/libnetfilter_conntrack pull request #1
Opened 2024-11-20 15:14 UTC by LaakkonenJussi

Create initial packaging, use the latest tagged version 1.1.0.

2024-11-23 17:10 UTC, Thaodan commented on rpm/libnetfilter_conntrack.spec
> +BuildRequires:  pkgconfig
pkgconfig requirement is redundant.

2025-08-04 11:31 UTC, LaakkonenJussi commented on rpm/libnetfilter_conntrack.spec
> +BuildRequires:  pkgconfig
Dropped with  ba7ec7d79016bd5adf70a1a9abf2c44510ab5b0c

2026-01-20 16:05 UTC, mlehtima requested changes

2026-01-20 16:05 UTC, mlehtima commented on rpm/libnetfilter_conntrack.spec
> +Requires:       libnfnetlink >= 1.0.2
Not needed as library dependency is automatically added during build.

2026-01-20 16:05 UTC, mlehtima commented on rpm/libnetfilter_conntrack.spec
> +BuildRequires:  gcc
We don't usually depend on gcc which is always installed in build environment.

2026-01-20 16:05 UTC, mlehtima commented on rpm/libnetfilter_conntrack.spec
> +BuildRequires:  libnfnetlink-devel >= 1.0.1
The devel packages could be done using pkgconfig(libmnl) and pkgconfig(libnfnetlink) to not depend on exact package names.

2026-01-20 16:05 UTC, mlehtima commented on rpm/libnetfilter_conntrack.spec
> +%{make_build}
We usually just use %make_build and %make_install without those {}. Same applies to the make_install below.

2026-01-21 16:26 UTC, LaakkonenJussi commented on rpm/libnetfilter_conntrack.spec
> +Requires:       libnfnetlink >= 1.0.2
Came from Fedora, dropped now.

2026-01-21 16:27 UTC, LaakkonenJussi commented on rpm/libnetfilter_conntrack.spec
> +BuildRequires:  gcc
Came from Fedora, dropped now.

2026-01-21 16:27 UTC, LaakkonenJussi commented on rpm/libnetfilter_conntrack.spec
> +BuildRequires:  libnfnetlink-devel >= 1.0.1
I wonder why Fedora did not have that, oh well, changed.

2026-01-21 16:28 UTC, LaakkonenJussi commented on rpm/libnetfilter_conntrack.spec
> +%{make_build}
Any reason why we just don't use and Fedora does? Anyways, dropped.

2026-01-21 16:33 UTC, mlehtima approved these changes

2026-04-08 11:05 UTC, direc85 approved these changes

2026-04-10 10:26 UTC, merged